name: Build React Docker image

on:
  push:
    branches: [ master ]

jobs:
  build-react:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - name: Install dependencies
        run: yarn install
      - name: Build frontend
        run: yarn run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: dist/

  build-docker:
    runs-on: ubuntu-latest
    needs:
      - build-react

    steps:
      - uses: actions/checkout@v2
      - name: Download built frontend
        uses: actions/download-artifact@v2
        with:
          name: website
          path: dist/
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.ruscalworld.ru
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.ruscalworld.ru/ruscalworld/ruscalworld:latest
          context: .