name: Build with NPM and Webpack

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - name: Install dependencies
        run: yarn install
      - name: Build frontend
        run: yarn run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: dist/